M48
; DRILL file {KiCad (5.99.0-10436-ga433451bd8)} date Thu May 13 10:32:16 2021
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-05-13T10:32:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-10436-ga433451bd8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X7.4134Y-3.8843
X7.4134Y-4.1118
T2
X7.5896Y-3.3553
X7.5896Y-3.4734
T0
M30
