M48
; DRILL file {KiCad (6.99.0-1239-g6d82490b59-dirty)} date Tue 22 Mar 2022 11:18:01 AM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-22T11:18:01-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.99.0-1239-g6d82490b59-dirty)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X9.2413Y-2.9439
X9.4689Y-2.9439
T0
M30
